---

- name: add vars depends on distr
  include_vars: "{{ ansible_os_family|lower }}.yml"

- name: checking requirements
  import_tasks: precheck.yml
  any_errors_fatal: yes

- name: do installation in custom dir
  block:
  - name: check directory {{ docker_custom_dir }}
    file:
      path: "{{ docker_custom_dir }}"
      state: directory
      owner: root
      group: root
  - name: create symlink for default docker dir
    file:
      src: "{{ docker_root }}/docker"
      dest: "/var/lib/docker"
      state: link
  when:
  - change_docker_dir|bool
  - docker_custom_dir is defined

- name: include tasks for configuring docker repo depends on distr
  include_tasks: "repocfg_{{ ansible_os_family|lower }}.yml"

- name: install {{ docker_package }}
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify:
  - restart_docker

- name: Ensure Docker is started and enabled at boot
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- name: manage docker users
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"

...